# Generated by Django 5.2.7 on 2025-10-17 18:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0002_profile'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Profile',
        ),
    ]
